- name: Creating Config file directory
  file: 
    path: /etc/rancher/rke2
    state: directory
    mode: '0755'

- name: Copy config.yml from ansible server to cluster workers
  copy:
    src: configs/config.yml
    dest: /etc/rancher/rke2/config.yaml
    owner: root
    group: root
