- name: Creating Config file directory
  file: 
    path: /etc/rancher/rke2
    state: directory
    mode: '0755'

- name: Copy server config from ansible server to cluster servers
  copy:
    src: configs/server-config.yml
    dest: /etc/rancher/rke2/config.yaml
    owner: root
    group: root
